version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      # 匿名登录
      - ALLOW_ANONYMOUS_LOGIN=yes
  # 具体配置参考 https://github.com/bitnami/bitnami-docker-kafka/blob/master/README.md
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://123.57.236.125:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认关闭)
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # Web 管理界面 感觉不是很好用 可以用这个exporter+grafana的方式 https://github.com/danielqsj/kafka_exporter
  kafka-manager:
    image: sheepkiller/kafka-manager
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
