apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: v2
  name: grpclb-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: v2
  name: grpclb-role
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grpclb-rolebinding
  namespace: v2
subjects:
  - kind: ServiceAccount
    name: grpclb-sa
    namespace: v2
roleRef:
  kind: Role
  name: grpclb-role
  apiGroup: rbac.authorization.k8s.io
