// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: region.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Region service

type RegionService interface {
	Ip2Region(ctx context.Context, in *RegionReq, opts ...client.CallOption) (*RegionResp, error)
}

type regionService struct {
	c    client.Client
	name string
}

func NewRegionService(name string, c client.Client) RegionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &regionService{
		c:    c,
		name: name,
	}
}

func (c *regionService) Ip2Region(ctx context.Context, in *RegionReq, opts ...client.CallOption) (*RegionResp, error) {
	req := c.c.NewRequest(c.name, "Region.Ip2Region", in)
	out := new(RegionResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Region service

type RegionHandler interface {
	Ip2Region(context.Context, *RegionReq, *RegionResp) error
}

func RegisterRegionHandler(s server.Server, hdlr RegionHandler, opts ...server.HandlerOption) error {
	type region interface {
		Ip2Region(ctx context.Context, in *RegionReq, out *RegionResp) error
	}
	type Region struct {
		region
	}
	h := &regionHandler{hdlr}
	return s.Handle(s.NewHandler(&Region{h}, opts...))
}

type regionHandler struct {
	RegionHandler
}

func (h *regionHandler) Ip2Region(ctx context.Context, in *RegionReq, out *RegionResp) error {
	return h.RegionHandler.Ip2Region(ctx, in, out)
}
