### 简单使用教程 https://www.freesion.com/article/7155384974/

### 新建账户
POST http://{{host}}{{baseUrl}}/accounts
Content-Type: application/json

{
  "userId": 2,
  "amount": 12.34
}

### 删除账户
DELETE http://{{host}}{{baseUrl}}accounts
Content-Type: application/json

{
  "userId": 7
}

### 更新账户
PUT http://{{host}}{{baseUrl}}accounts
Content-Type: application/json

{
  "userId": 8,
  "amount": 12.3456
}

### 查询账户
GET http://{{host}}{{baseUrl}}accounts/8
Content-Type: application/json


### 列表查询账户
GET http://{{host}}{{baseUrl}}accounts?page=1&size=20
Content-Type: application/json

###
