### 简单使用教程 https://www.freesion.com/article/7155384974/

### 新建账户
PUT http://{{host}}{{baseUrl}}/account
Content-Type: application/json

{
  "userId": 2,
  "amount": 12.34
}

### 删除账户
DELETE http://{{host}}{{baseUrl}}account
Content-Type: application/json

{
  "userId": 7
}

### 更新账户
POST http://{{host}}{{baseUrl}}account
Content-Type: application/json

{
  "userId": 8,
  "amount": 12.345
}

### 查询账户
GET http://{{host}}{{baseUrl}}account?userId=8
Content-Type: application/json


### 列表查询账户
GET http://{{host}}{{baseUrl}}account/list?page=1&size=20
Content-Type: application/json

###
