linters-settings:
  misspell:
    locale: US
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.17"
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: warning
      - name: add-constant
        severity: warning
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 15
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: -1
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: -1
# all linters see: https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose # checks whether HTTP response body is closed successfully
    - gocyclo
    - revive
    - goimports
    - misspell
    - gofmt
    - unused
    - typecheck
    - govet
    - ineffassign
    - gosimple
    - deadcode
    - structcheck
    - errcheck
    - funlen #	Tool for detection of long functions
service:
  golangci-lint-version: 1.43.0 # use the fixed version to not introduce new linters unexpectedly
