package core

type AutoGenerated struct {
	Data         Data `json:"data"`
	Success      bool `json:"success"`
	BizErrorCode int  `json:"bizErrorCode"`
}
type SharePictInfos struct {
	Type string `json:"type"`
	URL  string `json:"url"`
}
type URLTransInfo struct {
	URLText   string `json:"urlText"`
	URL       string `json:"url"`
	CouponURL string `json:"couponUrl"`
}
type QrCodeInfo struct {
	URLText   string `json:"urlText"`
	URL       string `json:"url"`
	CouponURL string `json:"couponUrl"`
}
type ShortLinkInfo struct {
	URLText   string `json:"urlText"`
	URL       string `json:"url"`
	CouponURL string `json:"couponUrl"`
}
type TaoTokenInfo struct {
	URLText             string `json:"urlText"`
	CouponTokenShortURL string `json:"couponTokenShortUrl"`
	URL                 string `json:"url"`
	TokenShortURL       string `json:"tokenShortUrl"`
	CouponURL           string `json:"couponUrl"`
}
type Data struct {
	SharePictInfos []SharePictInfos `json:"sharePictInfos"`
	URLTransInfo   URLTransInfo     `json:"urlTransInfo"`
	QrCodeInfo     QrCodeInfo       `json:"qrCodeInfo"`
	ShortLinkInfo  ShortLinkInfo    `json:"shortLinkInfo"`
	TaoTokenInfo   TaoTokenInfo     `json:"taoTokenInfo"`
}
type Result struct {
	ResultCode int  `json:"resultCode"`
	Data       Data `json:"data"`
}
