### 简单使用教程 https://www.freesion.com/article/7155384974/

### 新建用户
POST http://{{host}}{{baseUrl}}/users
Content-Type: application/json

{
  "name": "t",
  "age": 23,
  "pwd": "123456"
}

### 删除用户
DELETE http://{{host}}{{baseUrl}}users
Content-Type: application/json

{
  "id": 11
}

### 更新用户
PUT http://{{host}}{{baseUrl}}users
Content-Type: application/json

{
  "id": 8,
  "name": "first-new2",
  "phone": "10086",
  "pwd": "123456"
}

### 查询用户
GET http://{{host}}{{baseUrl}}users/8
Content-Type: application/json


### 列表查询
GET http://{{host}}{{baseUrl}}users?page=1&size=20
Content-Type: application/json

### xxx
