### 简单使用教程 https://www.freesion.com/article/7155384974/

### 新建用户
PUT http://{{host}}{{baseUrl}}/user
Content-Type: application/json

{
  "name": "second",
  "age": 23,
  "pwd": "654321"
}

### 删除用户
DELETE http://{{host}}{{baseUrl}}user
Content-Type: application/json

{
  "id": 1
}

### 更新用户
POST http://{{host}}{{baseUrl}}user
Content-Type: application/json

{
  "id": 1,
  "name": "first-new",
  "pwd": "123456"
}

### 查询用户
GET http://{{host}}{{baseUrl}}user?id=2
Content-Type: application/json


### 列表查询
GET http://{{host}}{{baseUrl}}user/list?page=1&size=20
Content-Type: application/json

### xxx
