### 简单使用教程 https://www.freesion.com/article/7155384974/


### 商品 id 查询
GET http://{{host}}{{baseUrl}}tbk?keyWords=614391759359
Content-Type: application/json

### 关键字 查询
GET http://{{host}}{{baseUrl}}tbk?keyWords=零食
Content-Type: application/json

###
