// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: bidirectional_stream.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AllStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number float64 `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *AllStreamReq) Reset() {
	*x = AllStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirectional_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStreamReq) ProtoMessage() {}

func (x *AllStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectional_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStreamReq.ProtoReflect.Descriptor instead.
func (*AllStreamReq) Descriptor() ([]byte, []int) {
	return file_bidirectional_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AllStreamReq) GetNumber() float64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type AllStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sqrt float64 `protobuf:"fixed64,1,opt,name=sqrt,proto3" json:"sqrt,omitempty"`
}

func (x *AllStreamResp) Reset() {
	*x = AllStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirectional_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStreamResp) ProtoMessage() {}

func (x *AllStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectional_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStreamResp.ProtoReflect.Descriptor instead.
func (*AllStreamResp) Descriptor() ([]byte, []int) {
	return file_bidirectional_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AllStreamResp) GetSqrt() float64 {
	if x != nil {
		return x.Sqrt
	}
	return 0
}

var File_bidirectional_stream_proto protoreflect.FileDescriptor

var file_bidirectional_stream_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x22, 0x26, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x71, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x71, 0x72,
	0x74, 0x32, 0x56, 0x0a, 0x19, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x39,
	0x0a, 0x04, 0x53, 0x71, 0x72, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x41, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidirectional_stream_proto_rawDescOnce sync.Once
	file_bidirectional_stream_proto_rawDescData = file_bidirectional_stream_proto_rawDesc
)

func file_bidirectional_stream_proto_rawDescGZIP() []byte {
	file_bidirectional_stream_proto_rawDescOnce.Do(func() {
		file_bidirectional_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidirectional_stream_proto_rawDescData)
	})
	return file_bidirectional_stream_proto_rawDescData
}

var file_bidirectional_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bidirectional_stream_proto_goTypes = []interface{}{
	(*AllStreamReq)(nil),  // 0: stream.AllStreamReq
	(*AllStreamResp)(nil), // 1: stream.AllStreamResp
}
var file_bidirectional_stream_proto_depIdxs = []int32{
	0, // 0: stream.BidirectionalStreamServer.Sqrt:input_type -> stream.AllStreamReq
	1, // 1: stream.BidirectionalStreamServer.Sqrt:output_type -> stream.AllStreamResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidirectional_stream_proto_init() }
func file_bidirectional_stream_proto_init() {
	if File_bidirectional_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidirectional_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidirectional_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidirectional_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidirectional_stream_proto_goTypes,
		DependencyIndexes: file_bidirectional_stream_proto_depIdxs,
		MessageInfos:      file_bidirectional_stream_proto_msgTypes,
	}.Build()
	File_bidirectional_stream_proto = out.File
	file_bidirectional_stream_proto_rawDesc = nil
	file_bidirectional_stream_proto_goTypes = nil
	file_bidirectional_stream_proto_depIdxs = nil
}
