// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: client_stream.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *ClientStreamReq) Reset() {
	*x = ClientStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamReq) ProtoMessage() {}

func (x *ClientStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamReq.ProtoReflect.Descriptor instead.
func (*ClientStreamReq) Descriptor() ([]byte, []int) {
	return file_client_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStreamReq) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ClientStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int64 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *ClientStreamResp) Reset() {
	*x = ClientStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResp) ProtoMessage() {}

func (x *ClientStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResp.ProtoReflect.Descriptor instead.
func (*ClientStreamResp) Descriptor() ([]byte, []int) {
	return file_client_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ClientStreamResp) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_client_stream_proto protoreflect.FileDescriptor

var file_client_stream_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x29, 0x0a,
	0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x32, 0x4c,
	0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x3c,
	0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_stream_proto_rawDescOnce sync.Once
	file_client_stream_proto_rawDescData = file_client_stream_proto_rawDesc
)

func file_client_stream_proto_rawDescGZIP() []byte {
	file_client_stream_proto_rawDescOnce.Do(func() {
		file_client_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_stream_proto_rawDescData)
	})
	return file_client_stream_proto_rawDescData
}

var file_client_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_stream_proto_goTypes = []interface{}{
	(*ClientStreamReq)(nil),  // 0: stream.ClientStreamReq
	(*ClientStreamResp)(nil), // 1: stream.ClientStreamResp
}
var file_client_stream_proto_depIdxs = []int32{
	0, // 0: stream.ClientStream.Sum:input_type -> stream.ClientStreamReq
	1, // 1: stream.ClientStream.Sum:output_type -> stream.ClientStreamResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_stream_proto_init() }
func file_client_stream_proto_init() {
	if File_client_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_stream_proto_goTypes,
		DependencyIndexes: file_client_stream_proto_depIdxs,
		MessageInfos:      file_client_stream_proto_msgTypes,
	}.Build()
	File_client_stream_proto = out.File
	file_client_stream_proto_rawDesc = nil
	file_client_stream_proto_goTypes = nil
	file_client_stream_proto_depIdxs = nil
}
