// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ClientStreamClient is the client API for ClientStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientStreamClient interface {
	// 客户端推送多个整数到服务端,服务端返回这些数之和
	Sum(ctx context.Context, opts ...grpc.CallOption) (ClientStream_SumClient, error)
}

type clientStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStreamClient(cc grpc.ClientConnInterface) ClientStreamClient {
	return &clientStreamClient{cc}
}

func (c *clientStreamClient) Sum(ctx context.Context, opts ...grpc.CallOption) (ClientStream_SumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClientStream_serviceDesc.Streams[0], "/stream.ClientStream/Sum", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientStreamSumClient{stream}
	return x, nil
}

type ClientStream_SumClient interface {
	Send(*ClientStreamReq) error
	CloseAndRecv() (*ClientStreamResp, error)
	grpc.ClientStream
}

type clientStreamSumClient struct {
	grpc.ClientStream
}

func (x *clientStreamSumClient) Send(m *ClientStreamReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientStreamSumClient) CloseAndRecv() (*ClientStreamResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientStreamResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStreamServer is the server API for ClientStream service.
// All implementations must embed UnimplementedClientStreamServer
// for forward compatibility
type ClientStreamServer interface {
	// 客户端推送多个整数到服务端,服务端返回这些数之和
	Sum(ClientStream_SumServer) error
	mustEmbedUnimplementedClientStreamServer()
}

// UnimplementedClientStreamServer must be embedded to have forward compatible implementations.
type UnimplementedClientStreamServer struct {
}

func (UnimplementedClientStreamServer) Sum(ClientStream_SumServer) error {
	return status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedClientStreamServer) mustEmbedUnimplementedClientStreamServer() {}

// UnsafeClientStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStreamServer will
// result in compilation errors.
type UnsafeClientStreamServer interface {
	mustEmbedUnimplementedClientStreamServer()
}

func RegisterClientStreamServer(s grpc.ServiceRegistrar, srv ClientStreamServer) {
	s.RegisterService(&_ClientStream_serviceDesc, srv)
}

func _ClientStream_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStreamServer).Sum(&clientStreamSumServer{stream})
}

type ClientStream_SumServer interface {
	SendAndClose(*ClientStreamResp) error
	Recv() (*ClientStreamReq, error)
	grpc.ServerStream
}

type clientStreamSumServer struct {
	grpc.ServerStream
}

func (x *clientStreamSumServer) SendAndClose(m *ClientStreamResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientStreamSumServer) Recv() (*ClientStreamReq, error) {
	m := new(ClientStreamReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ClientStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stream.ClientStream",
	HandlerType: (*ClientStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sum",
			Handler:       _ClientStream_Sum_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client_stream.proto",
}
