// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: server_stream.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServerStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *ServerStreamReq) Reset() {
	*x = ServerStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamReq) ProtoMessage() {}

func (x *ServerStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamReq.ProtoReflect.Descriptor instead.
func (*ServerStreamReq) Descriptor() ([]byte, []int) {
	return file_server_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStreamReq) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ServerStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *ServerStreamResp) Reset() {
	*x = ServerStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResp) ProtoMessage() {}

func (x *ServerStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResp.ProtoReflect.Descriptor instead.
func (*ServerStreamResp) Descriptor() ([]byte, []int) {
	return file_server_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStreamResp) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_server_stream_proto protoreflect.FileDescriptor

var file_server_stream_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x29, 0x0a,
	0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x32, 0x4c, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x3c, 0x0a, 0x03, 0x50, 0x6f, 0x77, 0x12, 0x17, 0x2e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_stream_proto_rawDescOnce sync.Once
	file_server_stream_proto_rawDescData = file_server_stream_proto_rawDesc
)

func file_server_stream_proto_rawDescGZIP() []byte {
	file_server_stream_proto_rawDescOnce.Do(func() {
		file_server_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_stream_proto_rawDescData)
	})
	return file_server_stream_proto_rawDescData
}

var file_server_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_stream_proto_goTypes = []interface{}{
	(*ServerStreamReq)(nil),  // 0: stream.ServerStreamReq
	(*ServerStreamResp)(nil), // 1: stream.ServerStreamResp
}
var file_server_stream_proto_depIdxs = []int32{
	0, // 0: stream.ServerStream.Pow:input_type -> stream.ServerStreamReq
	1, // 1: stream.ServerStream.Pow:output_type -> stream.ServerStreamResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_stream_proto_init() }
func file_server_stream_proto_init() {
	if File_server_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_stream_proto_goTypes,
		DependencyIndexes: file_server_stream_proto_depIdxs,
		MessageInfos:      file_server_stream_proto_msgTypes,
	}.Build()
	File_server_stream_proto = out.File
	file_server_stream_proto_rawDesc = nil
	file_server_stream_proto_goTypes = nil
	file_server_stream_proto_depIdxs = nil
}
