version: '3'
services:
  mongo-db:
    image: mongo
    restart: always
    # 自定义配置文件
    command: --config /etc/mongo/mongod.conf
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      # 日志 需要在宿主机修改为 777 权限容器里才能写入
      - ./log:/var/log/mongodb
      # 存储文件
      - ./db:/data/db
      # 配置文件
      - ./conf:/etc/mongo