version: '3'
services:
  mongo-db:
    image: mongo:latest
    # 只限制内存 其他用默认配置
#    command: --wiredTigerCacheSizeGB 1
    # 使用自定义配置文件 其他配置可以在配置文件中调整
    command: --config /data/configdb/mongod.conf
    container_name: mongodb
    #network_mode: "host"
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/data/db
      - ./backup:/data/backup
      - ./conf:/data/configdb