version: '3.2'
services:
  kibana:
    image: kibana:7.8.0
    container_name: elk-kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elk-es1:9200
      - I18N_LOCALE=zh-CN
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: elk
