# 1.setup node env
# 2.unit test
# 3.upload artifact

name: unit-test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

# This ensures that previous jobs for the PR are canceled when the PR is updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  jest-run:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: Jest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node env and build
        uses: actions/setup-node@v3
        with:
          node-version: 12.13
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Unit test
        run: yarn run test:unit:coverage
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: coverage/lcov-report/index.html