### 简单使用教程 https://www.freesion.com/article/7155384974/

### 新建订单
POST http://{{host}}{{baseUrl}}/orders
Content-Type: application/json

{
  "userId": 9,
  "amount": 1.234
}

### 删除订单
DELETE http://{{host}}{{baseUrl}}orders
Content-Type: application/json

{
  "id": 1
}

### 更新订单
PUT http://{{host}}{{baseUrl}}orders
Content-Type: application/json

{
  "id": 1,
  "userId": 9,
  "amount": 1.23456
}

### 查询订单
GET http://{{host}}{{baseUrl}}orders/1
Content-Type: application/json


### 列表查询订单
GET http://{{host}}{{baseUrl}}orders?userId=9&page=1&size=20
Content-Type: application/json

### xxx
### 列表查询订单
GET http://{{host}}{{baseUrl}}orders
Content-Type: application/json

### xxx
