### uppercase
GET http://localhost:8080/uppercase
Content-Type: application/json

{
 "s": "admin"
}

### count
GET http://localhost:8080/count
Content-Type: application/json

{
  "s": "hello, 17x"
}

### metrics
GET http://localhost:8080/metrics
Content-Type: application/json

{
  "s": "hello, 17x"
}

###